# Extensões
require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable
  Exclude:
    - db/schema.rb 
    - bin/bundle
    - spec/rails_helper.rb
    - config/initializers/*
    - config/environments/*
    - db/migrate/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 12