# Extensões
require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable
  Exclude:
    - db/schema.rb 
    - bin/bundle
    - config/environments/development.rb
    - spec/rails_helper.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false